apiVersion: v1
kind: Service
metadata:
  name: nginx-dev
  labels:
    env: dev
spec:
  type: LoadBalancer
  selector:
    app: nginx-dev
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-prod
  labels:
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: nginx-prod
  ports:
    - port: 80
      targetPort: 80