apiVersion: v1
kind: Secret
metadata:
  name: nginx-dev
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: dev-user
  password: dev-pass
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-prod
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: prod-user
  password: prod-pass